### ISSUE TITLE
Getting to Know Lean

### ISSUE THREAD

**Issue by OlingCat** [Lean-zh/fp-lean-zh#8]
- [x] 翻译
- [x] 校对

**Comment by edwardzcn-decade** [comment]
## Getting to Know Lean 翻译校对

两个URL链接翻译的状态不一致，以章节1.1为例[1.1. 表达式求值](https://lean.lookeng.cn/fp-lean/getting-to-know/evaluating.html)和[1.1. 求值表达式](https://www.leanprover.cn/fp-lean-zh/getting-to-know/evaluating.html)。

看起来`lean.lookeng.cn`域名下的翻译应该是先前版本，里面还带有一段无原文对照的翻译“它的本质是对下列语句进行证明：对于任意集合 S 和函数 f : S → ℝ，如果 f 是有界的......“，如果两个域名都在使用建议保持一致，CDN缓存的问题？
